# Generated by Django 6.0 on 2026-04-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='fname',
            field=models.CharField(default='noname', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='lname',
            field=models.CharField(default='noname', max_length=100),
        ),
    ]
