# Generated by Django 6.0 on 2026-04-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0004_economic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Economic',
        ),
    ]
